### ISSUE TITLE
Tried to run the module with a twitchtracker.

### ISSUE THREAD

**Issue by Disturbado** [tanersb/TwitchRecover#10]
Hi, I tried to run the module with one the links you posted as examples and I keep getting this. I also tried the VOD that I needed and had the same message.

Traceback (most recent call last):
  File "C:\Users\eduar\Desktop\proyectos\TwitchRecover-master\recover.py", line 6, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by tanersb** [comment]
@Disturbado What version of python are you using?

**Comment by ItsYaBoiRad** [comment]
Same problem, using the 3.11.0 ver

**Comment by tanersb** [comment]
> Same problem, using the 3.11.0 ver
> 

@ItsYaBoiRad Will you try using Pyhton version 3.7 or 3.6?

**Comment by davidruda** [comment]
@Disturbado @ItsYaBoiRad I had the same issue, you first have to run `pip install beautifulsoup4 requests` in the cmd line to install the missing packages. Then it should work. I'm using python 3.10 btw.

**Comment by ItsYaBoiRad** [comment]
@Davideck123 Thanks a lot mate! All i had to do was that and install requests and it works perfectly. Again, appreciate it mate
