### ISSUE TITLE
cloudflare bypass method

### ISSUE THREAD

**Issue by owk880301** [tanersb/TwitchRecover#14]
Hello I created a method can bypass cloudflare check out https://github.com/owk880301/TwitchRecover_cloudflare_bypass

**Comment by tanersb** [comment]
Hello! Thank you for sharing your work with me. I've checked out your method on your GitHub repository, and it looks interesting. If you create a fork of my repository and make the necessary modifications, I would be happy to review and approve it. Please let me know if you have any questions or need further assistance. Looking forward to collaborating with you!

**Comment by owk880301** [comment]
I forked your repository, further contact please add me on discord! S3rge#6584
