### ISSUE TITLE
New Twitch VOD domains

### ISSUE THREAD

**Issue by samoht0** [tanersb/TwitchRecover#2]
I noticed some unavailable VODs recently. Seems like there are new domains used.
https://github.com/TwitchRecover/TwitchRecover/issues/239
The problem appeared solved to me adding the domains to the script. I'd suggest to apply this change.

**Comment by tanersb** [comment]
Thank you, I will consider it.

**Comment by samoht0** [comment]
Fixed in https://github.com/tanersb/TwitchRecover/commit/e2766393447e9389a4270074ac7c010658977b69

**Comment by tanersb** [comment]
does it work ?

**Comment by samoht0** [comment]
Oh my, didn't test from master yesterday, as I had changed the script locally.
The script implies domains **without** a slash at the end. So... slash needs to be removed currently, to make it work. With that changed, yes, didn't see a single failure testing some VODs.

**Comment by tanersb** [comment]
I think it works now.

**Comment by lukeph11** [comment]
> I noticed some unavailable VODs recently. Seems like there are new domains used. [TwitchRecover/TwitchRecover#239](https://github.com/TwitchRecover/TwitchRecover/issues/239) The problem appeared solved to me adding the domains to the script. I'd suggest to apply this change.

Dont want to sound like a total bot but how do I access the script of the twitch recover program so I can edit it and then download the new exe with the new domains? Am I able to do this directly through github?
