### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by u2716** [tanersb/TwitchRecover#3]
python 3.10.5 , indexerror happens with both twitchtracker and streamcharts.

twitchtracker:
```Enter the link:https://twitchtracker.com/yungthasup/streams/39783759753
Date and Time are checking...
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/TwitchRecover/recover.py", line 270, in <module>
    timestamp = linkTimeCheck(link)
  File "/data/data/com.termux/files/home/TwitchRecover/recover.py", line 158, in linkTimeCheck
    print(f'Clock data:  {gelenveri[0].text}')
IndexError: list index out of range```

**Comment by u2716** [comment]
streamcharts:
```Enter the link:https://streamscharts.com/channels/yungthasup/streams/39783759753
Date and Time are checking..
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/TwitchRecover/recover.py", line 270, in <module>
    timestamp = linkTimeCheck(link)
  File "/data/data/com.termux/files/home/TwitchRecover/recover.py", line 80, in linkTimeCheck
    time = gelenveri[0].text
IndexError: list index out of range```

**Comment by u2716** [comment]
I tried the stream links in the readme.md too with same results.

**Comment by tanersb** [comment]
It doesn't give me any errors. works for me. Can you be sure that there is no excess in the link? and Can you send the links too?  @Victorbry99

**Comment by tanersb** [comment]
and there should be no spaces at the end of the link.

**Comment by u2716** [comment]
tried again. now it works. it was probably an extra space.

https://twitchtracker.com/yungthasup/streams/39783759753

give no results though. it's a stream that happened yesterday,so it should still be in their servers.

**Comment by tanersb** [comment]
The reason is that the broadcast was also deleted from the servers. The sooner you search after being deleted from Twitch, the more positive results you will get. 
It didn't work that way until a few days ago. I think it's stored in a different server. I was trying to solve this situation, but I lost hope.

**Comment by tanersb** [comment]
I would be grateful if you let me know if you learn anything. Have a good day.

**Comment by u2716** [comment]
thanks.
If I find new servers domains, I'll tell you.Right now I'm taking a look at the issue section of java twitchrecover project to see if anyone solved this problem.

**Comment by u2716** [comment]
It's strange. I'm getting indexerror again, with every link. I checked there are no extra spaces. I tried to add ```print = ('beg'+link+'end')``` and there are no extra spaces in the link printed ```beghttps://twitchtracker.com/yungthasup/streams/39783759753end``` .I tried also to do ```link.strip( )``` to remove spaces but same error again. have any idea how to debug it? maybe I'm doing something wromg and I don't see it.

**Comment by tanersb** [comment]
I'll look tomorrow for the problem you said. And i can try fix.

**Comment by u2716** [comment]
I added ```print(r)``` after ``` r = requests.get(link)``` and I get ```<Response [403]>``` using streamscharts links and  ```<Response [503]>``` using twitchtracker links. I think that's the problem.

**Comment by u2716** [comment]
error 503 seems  because I trigger ddos protection by cloudflare. if I do ```print(r.text)```, there is ```DDoS protection by <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a>```

**Comment by u2716** [comment]
now twitchtracker works again, streamscharts not. I tried implementing https://pypi.org/project/cloudscraper/ for bypassing cloudflare ddos protection that caused error 503 earlier on twitchtracker links.I don't know if it works yet.

**Comment by tanersb** [comment]
You can also enter the information manually if you want. Twitch name, hour, second,...
