### ISSUE TITLE
Script can't pass through cloudfare

### ISSUE THREAD

**Issue by DySt4f** [tanersb/TwitchRecover#4]
As the tittle says I think twitchtracker updated the protection to access the website since this week the site have been slowly working

Today as I was trying using the script in the morning it works fine, but then at night it just stop working, I enter twitchtracker and noticed the cloudfare protection message pop when it doesn't used to, so I just imagine now the script need an implementation to pass through it, I know there are some packages in python to properly resolve this but I don't really know how to implement them across this script

I'll gladly appreciate it if can help us with it, thanks for the good work

**Comment by tanersb** [comment]
yes, I noticed. and I'm trying to bypass it but I haven't had any more success. Anyone who can bypass can fork.

**Comment by tanersb** [comment]
import cloudscraper
import cfscrape
I tried with both, but I could not get a positive result.

**Comment by tanersb** [comment]
btw i noticed that from time to time it hangs on cloudflare. Not always . After waiting for a while, trying again, no error is received.

**Comment by DySt4f** [comment]
Yeah noticed this, prolly the days or hours with more traffic the website just dynamically blocks the access however as you say after a couple of tries it works again.
I'll mark this as complete and thanks again for being responsive.

**Comment by KaMyKaSii** [comment]
@tanersb you just need to pass a updated user agent with the request. You can hard code it in the script but this need the script to be updated with a new user agent after some time or make the script at every run parse a updated one from https://jnrbsn.github.io/user-agents/user-agents.json

**Comment by tanersb** [comment]
@KaMyKaSii thanks mate i will do what you say.
