### ISSUE TITLE
An error and a question

### ISSUE THREAD

**Issue by BrianJ20** [tanersb/TwitchRecover#6]
Love this software, but i have an issue that i would love to know if others have.

TwitchTracker works fine but StreamsCharts has never returned anything but an error for me.  Am using latest Python 3.10.5.

Up until 2 weeks ago i would get this error from StreamsCharts

`Date and Time are checking..
Traceback (most recent call last):
  File "C:\TwitchRecover\recover.py", line 270, in <module>
    timestamp = linkTimeCheck(link)
  File "C:\TwitchRecover\recover.py", line 80, in linkTimeCheck
    time = gelenveri[0].text
IndexError: list index out of range`

With the latest version i'm getting this error instead from StreamsCharts

`Date and Time are checking..
You probably got into cloudflare for bots.(could not find time data) There is nothing I can do for this error for now.
Please fork if you can bypass this cloudflare.
You will not get an error when you try again after a while.
So try again after a while.`

This error persists no matter when I retry, even after days of trying

This last thing is not a question about the software but about TwitchTracker.  When a stream gets disconnected and then starts up again, i've noticed that TwitchTracker lists it as only 1 long stream, but when you download it you end up with a file ending where the stream disconnected, with no way of getting the later parts.

An example is vodID 39417483079  TwitchTracker has it listed as a 2.1 hour stream but you end up with a 1 hour 20 min video.
StreamsCharts lists the same vodID 39417483079  as 1 hour 20 mins AND it also lists vodID 39417692487 with the remaining 50 mins.

Does anyone know how to use TwitchTracker to get the part after the disconnect ?  I've seen this problem many many times and it makes TwitchTracker very hard to use.

thank you for any help or advice.

**Comment by tanersb** [comment]
For your first question, I recommend using https://streamscharts.com.

**Comment by BrianJ20** [comment]
Sorry i misspelled streamscharts as streamcharts.   tbh i've never noticed the S before now and i've used the site for a long time.

Are you able to use it without errors ?

**Comment by tanersb** [comment]
It had support for two sites. I think it's still working but I haven't been able to check lately
