### ISSUE TITLE
Stream Title

### ISSUE THREAD

**Issue by mortyobnoxious** [tanersb/TwitchRecover#7]
Hi, is it possible to print **stream title**, too.

I looked at code but couldn't find a way to do it.

**Comment by tanersb** [comment]
Of course I'll fix it with a new update.

**Comment by tanersb** [comment]
I tried, but I couldn't pull the text under the span tag, If anyone has done it, send a request.

**Comment by mortyobnoxious** [comment]
I think the title is loaded later to website via js or sth. Maybe using a headless browser may help but it's too much for just printing title.
