### ISSUE TITLE
"No File Found on Twitch Servers."

### ISSUE THREAD

**Issue by hwwam** [tanersb/TwitchRecover#9]
Can you help me get m3u8 link to this stream??
i am getting "No File Found on Twitch Servers." message after running your script.
https://twitchtracker.com/adamcy_/streams/39951795448

**Comment by tanersb** [comment]
@hwwam Twitch streams are deleted after being stored on servers for a while. You have to be quick most of the time. It may have been permanently deleted from the server. the next time, if the broadcast on the twitch platform has been deleted, it can allow you to pull it from the servers with git.
